### ISSUE TITLE
Remove Specific tag

### ISSUE THREAD

**Issue by nochlab1** [technohiker/obsidian-multi-properties#15]
Thanks so much for this plugin was looking for something like tis for the longest time
was wondering if you can add a option to remove specific tags instead of all them

and when removing properties from folder it doesn't show to remove anything if there are only folders
like for example the way i have my structure is

Main folder
   Secondary
      actual notes

Thanks

**Comment by fez-github** [comment]
What do you mean remove specific tags?  You should already be able to do that, as you're provided a list of tags to choose from.

If I follow correctly on the second part, you're trying to remove tags starting with the main folder, and then go through every  subfolder and remove those as well?  In that case you're correct, it should be showing the props of the tags in those subfolders.  That will be addressed.

**Comment by nochlab1** [comment]
![Snipaste_2024-04-16_00-05-23](https://github.com/fez-github/obsidian-multi-properties/assets/37608994/5bbe7ad0-5263-475e-ae5e-54fefb29958b)

as you can there is a option to remove tags without letting me specify which tag just all of them

and the second issue you got correct

Thanks

**Comment by fez-github** [comment]
Ah, now I see.  That wasn't meant to be an option, it shouldn't have submitted anything if you did not pick any tags.  I could probably set up a button that will toggle all of them on by default, though.

**Comment by fez-github** [comment]
Finally got around to addressing this bug, but...now I'm curious as to how you were able to submit without confirming anything in the first place.  I had a check in place to make sure you couldn't.
![image](https://github.com/fez-github/obsidian-multi-properties/assets/75589254/b8d9100f-0d44-4c83-8633-41cbd54b3009)

**Comment by fez-github** [comment]
Turns out the bug wasn't an issue with properties within subfolders.  It wasn't removing properties on notes that only had a single property.  This should be addressed now.  Try this again in version 1.1.0.(may not be available in Community Plugins right away)
