### ISSUE TITLE
Text field breaks into list when it finds a comma

### ISSUE THREAD

**Issue by purierca** [technohiker/obsidian-multi-properties#18]
Hi, super useful plugin, thanks for it!
I'm updating properties with a text field, inputting a Templater template to then massively update my notes. However, Multi Properties breaks the Templater into a list when it finds a comma, regardless of how I wrap the entire text input.
Any way to fix this?

Here's what I input:
yesterday: [[<%tp.file.creation_date("YYYY-MM-DD",-1)%>]]
And what I get:
yesterday:
-   - '[[<%tp.file.creation_date("YYYY-MM-DD"'
  - -1)%>]]

**Comment by fez-github** [comment]
The plugin is currently set up to look for commas and use them as a delimiter to split a string of text into a list.  It's probably possible to make the delimiter changeable through Settings, with a comma as the default.  Shouldn't take too much work to refactor.  The code for splitting by commas can be found [here](https://github.com/fez-github/obsidian-multi-properties/blob/7a7927f799d3505d37f3c7c3a9670c0994352994/src/AddPropForm.svelte#L112C1-L112C31).

**Comment by fez-github** [comment]
This has been addressed in 1.1.0.  You can now go into the Settings tab and change the delimiter from a comma into whatever delimiter you want.
