### ISSUE TITLE
Don't add "empty" string if nothing is in the value field

### ISSUE THREAD

**Issue by 1ku1** [technohiker/obsidian-multi-properties#30]
Instead leave empty (null)

Inside the file it should just be

`property:`
rather than
`property: ""`

Thanks

**Comment by technohiker** [comment]
This has been implemented in [dev](https://github.com/technohiker/obsidian-multi-properties/blob/7f7e886140bb65827fb9c4bc5ec8d62bbec086bd/src/AddPropForm.svelte#L118) and will be in the next release.

**Comment by 1ku1** [comment]
Thank you.
