### ISSUE TITLE
[FR] bulk properties for internal link list

### ISSUE THREAD

**Issue by Friedolito** [technohiker/obsidian-multi-properties#35]
Thank you for creating this plug-in! 

I would love to have another function where to set properties for files that are listed as internal links. 

I often have the case that I have several notes belonging to a category (e.g. bones), but I can't select them trough the existing options (folder, files or search). 
They get there meaning of being in that list. 
I would love to select them and have a command in the context menu to "set property". 
![Screenshot -2024-12-14 at 12 17 11@2x](https://github.com/user-attachments/assets/2d840c83-c05d-4dfd-a22c-c61d1ea5897d)

Could this be feasable ? 
Think this could be useful for a lot of people in order to work in obsmd in a more DB kind of way. 

Best regards :)

**Comment by technohiker** [comment]
Thanks for the suggestion, but at the moment this is not feasible.  I assume what's happening in your image is you are on a note and that is all text with links on them, correct?  I like the idea, but afaik it can't be done.  

The way I add context menus for specific selections/folders is by using the `app.workspace.on` method to add a new menu whenever certain events occur, such as selecting a folder or group of files.  Unfortunately at this time there is no event that listens for when text is selected within a file.

**Comment by Friedolito** [comment]
Thanks for looking in to this! :)
